### ISSUE TITLE
Exposing metrics in ckb.toml 

### ISSUE THREAD

**Issue by robcxyz** [nervosnetwork/ckb#2388] opened 2020-12-02 23:38 UTC
I am trying to expose metrics to promtheus by adding the section [described in source](https://github.com/nervosnetwork/ckb/blob/develop/util/metrics-config/src/lib.rs#L13) to the ckb.toml as seen [here](https://github.com/insight-stratum/btcpool-docker-compose/blob/master/ckb-node/ckb.toml.example#L189) and I am not able to retrieve any metrics.  I am using the latest 0.38.1 image and the port is open but getting nothing from `curl localhost:8100/metrics`. 

Any ideas on this?  Thank you for your time.

**Comment by yangby-cryptape** [comment] 2020-12-03 05:58
Try `curl http://127.0.0.1:8100/`.

p.s. I tested your settings, it works.

**Comment by yangby-cryptape** [comment] 2020-12-03 06:04
I will close this issue. If you still have any problem about it, you can open this issue again.

p.s. This feature is not stable enough, we may update it. If you have any suggestions, feel free to tell us.

**Closed** 2020-12-03 06:04 UTC
Labels: t:question

**Comment by robcxyz** [comment] 2020-12-04 06:38
Unfortunately that did not work.  The I am running [this docker-compose](https://github.com/insight-nervos/btcpool-docker-compose/blob/master/docker-compose.yml) with [this ckb.toml](https://github.com/insight-nervos/btcpool-docker-compose/blob/master/ckb-node/ckb.toml#L188). Any help would be helpful as I am trying to build a grafana dashboard for pool operators with these metrics.  Thank you for your time.

**Comment by yangby-cryptape** [comment] 2020-12-04 06:56
You put several services together, and they didn't work well, I couldn't help you figure out with such a complex integration.

Please make a minimal demo to reproduce it:
- Just start CKB service with `ckb run -C .` without docker.
- Then open `http://127.0.0.1:8100/` in your browser.
- If you see some data in Prometheus format, it means CKB works well.

If CKB still doesn't work well, I will try my best to help you figure it out.
But if the problem isn't in CKB, since I'm not a docker or docker compose expert, I'm willing to help but unable to do so.

**Comment by keroro520** [comment] 2020-12-04 07:07
Try:

```toml
[metrics.exporter.prometheus]
target = { type = "http", listen_address = "0.0.0.0:8100" }
format = { type = "prometheus" }
```

It cannot access a local-listened only service from outside.

**Comment by robcxyz** [comment] 2020-12-04 08:44
@keroro520 - Ahh - solved. Thank you @yangby-cryptape, appreciate your time as well.
